INSERT INTO Author(AuthorID,AuthorName) VALUES(1,'Marcel Proust');
INSERT INTO Author(AuthorID,AuthorName) VALUES(2,'James Joyce');
INSERT INTO Author(AuthorID,AuthorName) VALUES(3,'Miguel de Cervantes');
INSERT INTO Author(AuthorID,AuthorName) VALUES(4,'Gabriel Garcia Marquez');
INSERT INTO Author(AuthorID,AuthorName) VALUES(5,'F. Scott Fitzgerald');
INSERT INTO Author(AuthorID,AuthorName) VALUES(6,'Herman Melville');
INSERT INTO Author(AuthorID,AuthorName) VALUES(7,'Leo Tolstoy');
INSERT INTO Author(AuthorID,AuthorName) VALUES(8,'William Shakespeare');
INSERT INTO Author(AuthorID,AuthorName) VALUES(9,'Homer');
INSERT INTO Author(AuthorID,AuthorName) VALUES(10,'Gustave Flaubert');
INSERT INTO Author(AuthorID,AuthorName) VALUES(11,'Dante Alighieri');
INSERT INTO Author(AuthorID,AuthorName) VALUES(12,'Vladimir Nabokov');
INSERT INTO Author(AuthorID,AuthorName) VALUES(13,' Fyodor Dostoyevsky');
INSERT INTO Author(AuthorID,AuthorName) VALUES(14,' Emily Brontë');
INSERT INTO Author(AuthorID,AuthorName) VALUES(15,' J. D. Salinger');
INSERT INTO Author(AuthorID,AuthorName) VALUES(16,'Jane Austen');
INSERT INTO Author(AuthorID,AuthorName) VALUES(17,'Mark Twain');
INSERT INTO Author(AuthorID,AuthorName) VALUES(18,' Laurence Sterne');
INSERT INTO Author(AuthorID,AuthorName) VALUES(19,'Stendhal');
INSERT INTO Author(AuthorID,AuthorName) VALUES(20,'Virginia Woolf');
INSERT INTO Author(AuthorID,AuthorName) VALUES(21,'Joseph Heller');
INSERT INTO Author(AuthorID,AuthorName) VALUES(22,'Joseph Conrad');
INSERT INTO Author(AuthorID,AuthorName) VALUES(23,'William Faulkner');
INSERT INTO Author(AuthorID,AuthorName) VALUES(24,'George Orwell');
INSERT INTO Author(AuthorID,AuthorName) VALUES(25,' Charles Dickens');
INSERT INTO Author(AuthorID,AuthorName) VALUES(26,'John Steinbeck');
INSERT INTO Author(AuthorID,AuthorName) VALUES(27,'Ralph Ellison');
INSERT INTO Author(AuthorID,AuthorName) VALUES(28,'Harper Lee');
INSERT INTO Author(AuthorID,AuthorName) VALUES(29,' Franz Kafka');
INSERT INTO Author(AuthorID,AuthorName) VALUES(30,'George Eliot');
INSERT INTO Author(AuthorID,AuthorName) VALUES(31,'Jonathan Swift');
INSERT INTO Author(AuthorID,AuthorName) VALUES(32,'Toni Morrison');
INSERT INTO Author(AuthorID,AuthorName) VALUES(33,'Thomas Mann');
INSERT INTO Author(AuthorID,AuthorName) VALUES(34,'Anton Chekhov');
INSERT INTO Author(AuthorID,AuthorName) VALUES(35,'Albert Camus');
INSERT INTO Author(AuthorID,AuthorName) VALUES(36,'Charlotte Bronte');
INSERT INTO Author(AuthorID,AuthorName) VALUES(37,'Virgil');
INSERT INTO Author(AuthorID,AuthorName) VALUES(38,'Jorge Luis Borges');
INSERT INTO Author(AuthorID,AuthorName) VALUES(39,'Ernest Hemingway');
INSERT INTO Author(AuthorID,AuthorName) VALUES(40,'Salman Rushdie');
