INSERT INTO Category(CategoryID,CategoryDescription) VALUES(1,'These books will tend to fit epic tales of grand journeys best. They tend to lack specific elements of other genres, like fantasy creatures and sci-fi elements, but a few can be found in these books as well.');
INSERT INTO Category(CategoryID,CategoryDescription) VALUES(2,'These books were created with young children in mind, ranging from those learning how to read to those slowly progressing to bigger books. ');
INSERT INTO Category(CategoryID,CategoryDescription) VALUES(3,'These books are the most dependent on context. Most of these do have darker words and thus a darker feel to them.');
INSERT INTO Category(CategoryID,CategoryDescription) VALUES(4,'These books have a lot of fantasy related elements, like fantasy creatures and magic. These elements make the books different from the adventure one, but these 2 categories share quite a few other elements.');
INSERT INTO Category(CategoryID,CategoryDescription) VALUES(5,'These books were created with ghost stories in mind. Think creepypasta and stories you may have heard or told your friends around a campfire or during a sleepover.');
INSERT INTO Category(CategoryID,CategoryDescription) VALUES(6,'These books contain more elements which try to make it odd or funny, and thus reflect the story itself.');
INSERT INTO Category(CategoryID,CategoryDescription) VALUES(7,'These books are all about secrets, hidden treasures, and other mysteries. Like the drama ones, these also depend a lot on context.');
INSERT INTO Category(CategoryID,CategoryDescription) VALUES(8,'These books are, of course, about love. But also about the pain that comes with a break up, as well as stories in which love is the main theme, but not necessarily the plot.');
INSERT INTO Category(CategoryID,CategoryDescription) VALUES(9,'These books will fit the futuristic stories best. Aliens, space travel, robotic enslavement, and all the other common themes can be found here.');
