INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(1,'Kellie','Ramirez',10016,'New York','New York' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(2,'Gabriel','Gutierrez',77005,'Houston','Texas' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(3,'Luther','Holt',94123,'San Francisco','California' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(4,'Terry ','Johnson',10022,'New York','New York' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(5,'Al','Erickson',85088,'Phoenix','Arizona' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(6,'Janet','Stokes',77037,'Houston','Texas' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(7,'Kerry','Lane',90095,'Los Angeles','California' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(8,'Rick ','Shelton',10060,'New York','New York' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(9,'Paula','Christensen',94115,'San Francisco','California' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(10,'Margaret','Barton',87125,'Albuquerque','New Mexico' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(11,'Ora','Silva',77076,'Houston','Texas' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(12,'Deanna','Jimenez',60827,'Chicago','Illinois' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(13,'Viola','Davis',10090,'New York','New York' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(14,'Tracey','Rice',85025,'Phoenix','Arizona' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(15,'Barry','Kelly',94144,'San Francisco','California' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(16,'Robin','Herrera',90077,'Los Angeles','California' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(17,'Rosie','Berry',77098,'Houston','Texas' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(18,'Myron','Parks',87199,'Albuquerque','New Mexico' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(19,'Marcos','Nelson',50981,'Des Moines','Iowa' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(20,'Evelyn','Cain',10117,'New York','New York' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(21,'Carroll','Cook',60610,'Chicago','Illinois' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(22,'Rachel','Higgins',94156,'San Francisco','California' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(23,'Noah','Sandoval',60131,'Chicago','Illinois' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(24,'Sherman','Montgomery',10123,'New York','New York' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(25,'Caleb','Elliott',90089,'Los Angeles','California' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(26,'Dewey','Mendoza',87153,'Albuquerque','New Mexico' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(27,'Grace','Foster',94164,'San Francisco','California' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(28,'Gregg ','Adkins',50312,'Des Moines','Iowa' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(29,'Willie','Alguiler',77085,'Houston','Texas' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(30,'Terrance','Manning',60622,'Chicago','Illinois' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(31,'Cornelius','Nunez',85065,'Phoenix','Arizona' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(32,'Roberta','Douglas',50393,'Des Moines','Iowa' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(33,'Wilson','Barnes',94188,'San Francisco','California' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(34,'Rogelio','Bates',90059,'Los Angeles','California' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(35,'Forrest','Castillo',50360,'Des Moines','Iowa' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(36,'Harold','Larson',77202,'Houston','Texas' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(37,'Wilbert','Newton',60632,'Chicago','Illinois' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(38,'Ervin','Fowler',85072,'Phoenix','Arizona' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(39,'Maryann','Guerrero',90048,'Los Angeles','California' );
INSERT INTO Customer(CustomerID, Firstname, Lastname, Zipcode, City, StateP) VALUES(40,'Jennifer','Meyer',60699,'Chicago','Illinois' );
