/*
SELECCION DE DATOS DE EMPLEADO DEL ESQUEMA CURSODB
*/
SELECT * FROM EMPLEADO;



INSERT INTO EMPLEADO(IDEMPLEADO,PATERNO,MATERNO,NOMBRE,GENERO,RFC,CURP,NUMIMSS,FECHAALTA)
VALUES(855,'FLORES','RODRIGUEZ','ONESIMO','H','FORO460903937','FORO460903HCLLDN00','855'
,TO_DATE('16/10/1986','DD/MM/YYYY'));


INSERT INTO EMPLEADO(IDEMPLEADO,PATERNO,MATERNO,NOMBRE,GENERO,RFC,CURP,NUMIMSS,FECHAALTA)
VALUES(975,'GONZALEZ','ALANIS','ARIEL HECTOR','H','GOAA440717TR5','GOAA440717HCLNLR00','975'
,TO_DATE('01/01/1967','DD/MM/YYYY'));


/*
CREAR TABLA DE EMPLEADO DEL ESQUEMA CURSODB
*/
CREATE TABLE EMPLEADO
(
IDEMPLEADO NUMBER NOT NULL,
PATERNO VARCHAR2(50) NOT NULL,
MATERNO VARCHAR2(50) NOT NULL,
NOMBRE VARCHAR2(50) NOT NULL,
GENERO VARCHAR2(1) NOT NULL,
RFC VARCHAR2(13) NOT NULL,
CURP VARCHAR2(18) NOT NULL,
NUMIMSS VARCHAR2(11) NOT NULL,
FECHAALTA DATE NOT NULL,
CONSTRAINT EMPLEADO_PK PRIMARY KEY(IDEMPLEADO)
);

/*
BORRAR REGISTROS DE EMPLEADO DEL ESQUEMA CURSODB
*/
DELETE FROM EMPLEADO WHERE IDEMPLEADO=855;
DELETE FROM EMPLEADO WHERE IDEMPLEADO=975;

/*
BORRAR CONTENIDO DE EMPLEADO DEL ESQUEMA CURSODB
*/
TRUNCATE TABLE EMPLEADO;

/*
BORRAR ESTRUCTURA Y CONTENIDO DE EMPLEADO DEL ESQUEMA CURSODB
*/
DROP TABLE EMPLEADO;