SELECT COUNT(IDEMPLEADO) CANT FROM EMPLEADO WHERE GENERO = 'H';
SELECT COUNT(IDEMPLEADO) CANT FROM EMPLEADO WHERE GENERO = 'M';

SELECT GENERO,
CASE WHEN GENERO = 'H' THEN 1 ELSE 0 END T_HOMBRE,
CASE WHEN GENERO = 'M' THEN 1 ELSE 0 END T_MUJER
FROM EMPLEADO;

SELECT GENERO,
COUNT(CASE WHEN GENERO = 'H' THEN 1 END)T_HOMBRE,
COUNT(CASE WHEN GENERO = 'M' THEN 1 END)T_MUJER
FROM EMPLEADO;


/*
OBTENER LA LISTA DE EMPLEADOS QUE INGRESARON ENTRE 01/05/1979 AL 25/10/1984
*/
SELECT * FROM EMPLEADO 
WHERE FECHAALTA BETWEEN TO_DATE('01/05/1979', 'DD/MM/YYYY') AND TO_DATE('25/10/1984', 'DD/MM/YYYY');

/*
OBTENER LA LISTA DE LOS EMPLEADOS QUE NACIERON ENTRE 1960 Y 1990
*/
SELECT * FROM EMPLEADO WHERE SUBSTR(RFC, 5, 2) BETWEEN '60' AND '90';

/*
OBTENER CUANTOS EMPLEADOS TIENE LA TABLA DE EMPLEADOS CON INGRESO EN LA DECADA DE LOS 90's
*/
SELECT * FROM EMPLEADO WHERE FECHAALTA BETWEEN TO_DATE('01/01/1990', 'DD/MM/YYYY') AND TO_DATE('31/12/1999', 'DD/MM/YYYY');