/*MOSTRAR NOMBRE DE LA MARCA EN CADA ARTICULO*/
SELECT A.IDARTICULO, A.CODIGO, A.DESCRIPCION, A.IDMARCA,
(SELECT MARCA FROM MARCA WHERE IDMARCA = A.IDMARCA) MARCA,
A.COSTO, A.PRECIO, A.REORDEN FROM ARTICULO A; 

/*MOSTRAR NOMBRE DE LA MARCA EN CADA ARTICULO*/
SELECT A.IDARTICULO, A.CODIGO, A.DESCRIPCION, A.IDMARCA,
M.MARCA, A.COSTO, A.PRECIO, A.REORDEN
FROM ARTICULO A
INNER JOIN MARCA M ON M.IDMARCA = A.IDMARCA;

/*CREAR UNA VISTA*/
CREATE OR REPLACE VIEW V_ARTICONMARCA AS
SELECT A.IDARTICULO, A.CODIGO, SUBSTR(A.DESCRIPCION,1,150) DESCRIPCION,
A.IDMARCA, M.MARCA, A.COSTO, A.PRECIO, A.REORDEN
FROM ARTICULO A
INNER JOIN MARCA M ON M.IDMARCA = A.IDMARCA;

SELECT * FROM V_ARTICONMARCA;

/*CUANTOS ARTICULOS MANEJA CADA MARCA*/
SELECT IDMARCA, MARCA, COUNT(IDARTICULO) CANT
FROM V_ARTICONMARCA
GROUP BY IDMARCA, MARCA
ORDER BY IDMARCA, MARCA;



SELECT IDEMPLEADO, (NOMBRE || ' ' || PATERNO || ' ' || MATERNO) NOMBRE_COMP
FROM EMPLEADO WHERE GEENERO = 'M'
ORDER BY NOMBRE_COMP;


/*CREAR UNA FUNCION*/
CREATE FUNCTION FN_NOMBRECOMP(pIDEMP NUMBER, pOP NUMBER) RETURN VARCHAR2 AS
wPATERNO VARCHAR(50);
wMATERNO VARCHAR(50);
wNOMBRE VARCHAR(50);
BEGIN
SELECT PATERNO, MATERNO, NOMBRE INTO wPATERNO, wMATERNO, wNOMBRE
FROM EMPLEADO WHERE IDEMPLEADO = pIDEMP;
IF pOP = 0 THEN 
RETURN (wPATERNO || ' ' || wMATERNO || ' ' || wNOMBRE);
END IF;
IF pOP = 1 THEN
RETURN (wNOMBRE || ' ' || wPATERNO || ' ' || wMATERNO);
END IF;
END;

SELECT FN_NOMBRECOMP(855,0) NOM_F1, FN_NOMBRECOMP(855,1) NOM_F2 FROM DUAL;



TRUNCATE TABLE ENTRADA;
SELECT * FROM ENTRADA;



