CREATE TABLE MARCA (
IDMARCA NUMBER NOT NULL,
MARCA VARCHAR2(50) NOT NULL,
CONSTRAINT MARCA_PK PRIMARY KEY (IDMARCA)
);


CREATE TABLE ARTICULO (
IDARTICULO NUMBER NOT NULL,
CODIGO VARCHAR2(20) NOT NULL,
DESCRIPCION VARCHAR2(200) NOT NULL,
IDMARCA NUMBER NOT NULL,
COSTO NUMBER NOT NULL,
PRECIO NUMBER NOT NULL,
REORDEN NUMBER NOT NULL,
CONSTRAINT ARTICULO_PK PRIMARY KEY (IDARTICULO),
CONSTRAINT ARTICULO_MARCA_FK1 FOREIGN KEY (IDMARCA) REFERENCES MARCA (IDMARCA)
);


CREATE TABLE ENTRADA (
IDENTRADA NUMBER NOT NULL,
IDARTICULO NUMBER NOT NULL,
CANTIDAD NUMBER NOT NULL,
COSTO NUMBER NOT NULL,
PRECIO NUMBER NOT NULL,
FECHAENTRADA DATE NOT NULL,
CONSTRAINT ENTRADA_PK PRIMARY KEY (IDENTRADA),
CONSTRAINT ARTICULO_ENTRADA_FK1 FOREIGN KEY (IDARTICULO) REFERENCES ARTICULO (IDARTICULO)
);


CREATE TABLE SALIDA (
IDSALIDA NUMBER NOT NULL,
IDARTICULO NUMBER NOT NULL,
CANTIDAD NUMBER NOT NULL,
COSTO NUMBER NOT NULL,
PRECIO NUMBER NOT NULL,
FECHASALIDA DATE NOT NULL,
CONSTRAINT SALIDA_PK PRIMARY KEY (IDSALIDA),
CONSTRAINT SALIDA_ARTICULO_FK1 FOREIGN KEY (IDARTICULO) REFERENCES ARTICULO (IDARTICULO)
);

SELECT * FROM MARCA;
SELECT * FROM ARTICULO;

DELETE FROM ARTICULO;