select * from articulo;

SELECT FN_ARTI_UT(125) UT FROM DUAL;

/*     obtener la utilidad por articulo

UTILIDAD = ( 1-(COSTO/PRESIO))*100 REDONDEAR A 2 DECIMALES

*/ 
/* 

CONTRUIR UNA FUNCION PARA SACAR LA UTILIDAD 

*/

CREATE OR REPLACE VIEW V_ARTICULO_UT AS
SELECT A.IDARTICULO,A.CODIGO,A.DESCRIPCION,A.IDMARCA,M.MARCA,A.COSTO,A.PRECIO
,ROUND((1-(A.COSTO/A.PRECIO))*100,2) UT_ART,A.REORDEN
FROM ARTICULO A
INNER JOIN MARCA M ON M.IDMARCA=A.IDMARCA
;



CREATE OR REPLACE FUNCTION FN_ARTI_UT(pIDARTI NUMBER) RETURN NUMBER AS 
wCOSTO NUMBER;
wPRECIO NUMBER;

BEGIN
SELECT COSTO,PRECIO INTO wCOSTO, wPRECIO from ARTICULO 
WHERE IDARTICULO = pIDARTI;
RETURN ROUND ((1-(wCOSTO/wPRECIO))*100, 2);
END;







