/*
SELECCION DE EMPLEADOS DEL ESQUEMA HR
*/
SELECT * FROM EMPLOYEES
WHERE SALARY BETWEEN 2500 AND 5000
;


SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES
ORDER BY FIRST_NAME
;